-- Insertion des auteurs
INSERT INTO AUTHORS (AUTHOR_FIRSTNAME, AUTHOR_LASTNAME) VALUES ('Eric', 'John');
INSERT INTO AUTHORS (AUTHOR_FIRSTNAME, AUTHOR_LASTNAME) VALUES ('Smith', 'Jane');
INSERT INTO AUTHORS (AUTHOR_FIRSTNAME, AUTHOR_LASTNAME) VALUES ('Martin', 'Robert');

-- Insertion des livres
INSERT INTO BOOKS (BOOK_TITLE, BOOK_PRICE, BOOK_DATE_PUBLICATION, author_fk) VALUES ('Spring Boot in Action', 29.99, '2018-01-01', 1);
INSERT INTO BOOKS (BOOK_TITLE, BOOK_PRICE, BOOK_DATE_PUBLICATION, author_fk) VALUES ('Java Concurrency in Practice', 39.99, '2015-05-20', 2);
INSERT INTO BOOKS (BOOK_TITLE, BOOK_PRICE, BOOK_DATE_PUBLICATION, author_fk) VALUES ('Effective Java', 49.99, '2018-12-27', 3);